//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SapBydSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class journal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public journal()
        {
            this.gen_ledger = new HashSet<gen_ledger>();
        }
    
        public string C_uid { get; set; }
        public string jour_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> changed_date { get; set; }
        public Nullable<int> debit_credit { get; set; }
        public Nullable<int> fiscal_year { get; set; }
        public string gl_acct { get; set; }
        public string gl_acct_type { get; set; }
        public string created_by { get; set; }
        public string changed_by { get; set; }
        public Nullable<long> comp_cur_amt { get; set; }
        public Nullable<long> item_cur_amt { get; set; }
        public Nullable<long> tran_cur_amt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gen_ledger> gen_ledger { get; set; }
    }
}
